/**
 * Bundles `action.mjs` with the parser and everything it imports into `actions/mod-ini/dist/action.mjs`, which is
 * committed: an action runs from the ZAX repository at the caller's pinned ref, with nothing installed. CI rebuilds
 * it and fails on any difference (`.github/scripts/check-generated.sh`), so the bundle cannot drift from its source.
 */

import { build } from "esbuild";
import { fileURLToPath } from "node:url";

await build({
  // The bundle's path comments are relative to this, so pinning it keeps the output the same from any directory.
  absWorkingDir: fileURLToPath(new URL("../..", import.meta.url)),
  entryPoints: [fileURLToPath(new URL("action.mjs", import.meta.url))],
  outfile: fileURLToPath(new URL("../../actions/mod-ini/dist/action.mjs", import.meta.url)),
  bundle: true,
  platform: "node",
  format: "esm",
  // The action's own runtime is node24; `pack-mod` runs the same file on whatever Node its runner has.
  target: "node20",
  // `yaml` resolves to its CommonJS build under Node, which esbuild inlines with a `require` shim that cannot load
  // Node's built-ins from an ESM output - the same gap `packages/app/build.mjs` closes the same way.
  banner: {
    js: [
      "// Generated by scripts/mod-ini/build.mjs - edit the sources there, then rebuild.",
      "import { createRequire as zaxCreateRequire } from 'node:module';",
      "const require = zaxCreateRequire(import.meta.url);",
    ].join("\n"),
  },
  logLevel: "warning",
});
