// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionGroup } from "./ActionGroup";
import type { WineSetting } from "./WineSetting";

export type Action = { id: string, label: string, group: ActionGroup, 
/**
 * What the user gets, in their language. Not a list of the keys involved.
 */
description: string, 
/**
 * Setting id to the value this action writes.
 */
targets: { [key in string]: string }, 
/**
 * Button wording once every target already matches.
 */
appliedLabel: string, wine: WineSetting | null, };
