// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an action is offered.
 *
 * Declared on the action rather than listed by the panel that shows it: a panel holding its own
 * list of ids silently drops any action added afterwards, which is how one of these came to exist
 * in the catalog and appear nowhere in the interface.
 */
export type ActionGroup = "report" | "fix";
