// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A one-click fix as its card draws it.
 */
export type ActionView = { id: string, applied: boolean, 
/**
 * How many of its targets do not yet hold what it writes.
 */
pending: number, };
