// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateView } from "./GateView";
import type { LinkedAddress } from "./LinkedAddress";
import type { Requirement } from "./Requirement";
import type { SettingTarget } from "./SettingTarget";

/**
 * A row as one group of tabs shows it. A linked setting is a different key, under a different gate,
 * on each component's tab.
 */
export type AddressView = { target: SettingTarget, 
/**
 * Whether the install has the file this address is in.
 */
hasFile: boolean, gate: GateView | null, 
/**
 * Everything the gate waits on, nearest first, or `None` where one of them cannot be set from
 * here - a pinned value, a missing file, a gate naming no single value, or a cycle.
 */
requirements: Array<Requirement> | null, linked: Array<LinkedAddress>, };
