// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppView } from "./AppView";

/**
 * The view, and a sentence about what the operation refused or reported.
 */
export type Answered<T> = { view: AppView, answer: T, };
