// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Install } from "./Install";
import type { StoredInstall } from "./StoredInstall";
import type { Theme } from "./Theme";

export type AppState = { 
/**
 * Installs that are on the list and readable now, with the type read from the directory.
 */
installs: Array<Install>, 
/**
 * Installs on the list that could not be read - an unplugged drive, a folder moved since last
 * time. Kept rather than dropped, because writing the file back without them would turn a drive
 * being offline for one session into losing the entry permanently.
 */
unavailable: Array<StoredInstall>, theme: Theme, autosave: boolean, 
/**
 * Engines whose caution has been dismissed - see [`ZaxFile`], which is where the shape is
 * explained.
 */
acceptedCautions: Array<string>, };
