// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineListing } from "./EngineListing";
import type { EngineRelease } from "./EngineRelease";
import type { Install } from "./Install";
import type { MachineDescription } from "./MachineDescription";
import type { ReadingView } from "./ReadingView";
import type { SfallRelease } from "./SfallRelease";
import type { Theme } from "./Theme";

/**
 * Everything the interface draws, as of one revision.
 */
export type AppView = { 
/**
 * Higher is newer. An answer carrying a lower one than the view on screen is stale.
 */
revision: number, machine: MachineDescription, installs: Array<Install>, theme: Theme, autosave: boolean, acceptedCautions: Array<string>, 
/**
 * The selected install's path, or empty with none.
 */
selected: string, engines: Array<EngineListing>, engineLatest: { [key in string]: EngineRelease }, sfallLatest: SfallRelease | null, zaxLatest: string | null, 
/**
 * Whether the release found is newer than the ZAX that is running.
 */
zaxOutdated: boolean, reading: ReadingView | null, };
