// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The processor a build has to match. `Other` is every architecture ZAX names no build for, which
 * is a real answer rather than a gap: a caller with no build for the pair falls back to a portable
 * one, and a wrong guess here would hand a host a binary it cannot execute.
 */
export type Architecture = "x64" | "arm64" | "other";
