// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModType } from "./ModType";

/**
 * What the interface offers for one mod on one install, decided from what is already known.
 *
 * Tagged with the kind, which is the field every surface branches on, and spelled the way the
 * interface reads it: `install-over` rather than `installOver`, as the TypeScript named them.
 */
export type Availability = { "kind": "install" } | { "kind": "install-over" } | { "kind": "nightly", commit: string, } | { "kind": "installed" } | { "kind": "upgrade", from: string, } | { "kind": "convert", from: string, was: ModType, } | { "kind": "downgrade", from: string, } | { "kind": "retry", version: string, } | { "kind": "unfollowed" } | { "kind": "blocked", why: string, from: string | null, };
