// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameType } from "./GameType";
import type { InstallerRoute } from "./InstallerRoute";

/**
 * What installing a base mod would do, as far as anything but the installer can say. Thinner than a
 * stacking mod's plan on purpose, and the plan says so: the installer decides what lands, so naming
 * files here would be inventing them.
 */
export type BaseInstallPlan = { version: string, 
/**
 * The asset that installs it, and which of the two routes it takes.
 */
asset: string, route: InstallerRoute, 
/**
 * What the download needs, from what the release states about the asset.
 */
download: bigint, 
/**
 * What the payload unpacks to, where the route lets ZAX read that before running anything.
 */
unpacked: bigint | null, 
/**
 * Free bytes on the game's filesystem, where the host could say.
 */
free: bigint | null, 
/**
 * How many entries the case-lowering pass would rename before the install runs. Absent where the
 * pass does not apply - a filesystem that folds case, or an install that is already this mod's.
 */
lowercasing: number | null, 
/**
 * The game type the install reports afterwards.
 */
becomes: GameType, fingerprint: string, };
