// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameType } from "./GameType";
import type { MergeConflict } from "./MergeConflict";

/**
 * What a finished base install leaves the caller to act on.
 */
export type BaseInstallOutcome = { version: string, 
/**
 * What the install now is - the caller re-reads the directory to confirm it.
 */
becomes: GameType, 
/**
 * How many entries the case-lowering pass renamed before the installer ran.
 */
renamed: number, 
/**
 * Settings both the user and the release changed; the user's won.
 */
conflicts: Array<MergeConflict>, 
/**
 * Where the installer keeps its own copy of what it moved aside.
 */
backup: string, };
