// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a user picked for a folder: one build by its publication instant, or `Latest` to clear a pin
 * and follow the newest build the machine holds. Two variants rather than two strings, since a tag
 * could be spelled `latest` and an instant cannot be told from one by type.
 */
export type BuildPick = { "pick": "published" } & string | { "pick": "latest" };
