// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One build the machine holds, as a version list needs it. Addressed by `published`, not by tag.
 */
export type CachedBuild = { 
/**
 * The release's tag, as published. A rolling project republishes one, so it does not identify a
 * build.
 */
release: string, 
/**
 * When it was published, ISO 8601. The key a build is asked for by.
 */
published: string, commit: string | null, };
