// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an install stands in a release's choices: what to install, what went, and whether to ask.
 */
export type CarriedSelection = { 
/**
 * The parts to install, in declared order - the recorded choice re-matched against this release.
 */
selection: Array<string>, 
/**
 * Recorded parts this release no longer offers. Named before the upgrade runs, never silently.
 */
dropped: Array<string>, 
/**
 * Whether the choice has to be put to the user rather than carried over.
 */
ask: boolean, };
