// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { GameTypeView } from "./GameTypeView";
import type { LayoutFile } from "./LayoutFile";
import type { ResolutionView } from "./ResolutionView";
import type { SettingDef } from "./SettingDef";

export type CatalogView = { settings: Array<SettingDef>, layout: Array<LayoutFile>, actions: Array<Action>, resolutions: Array<ResolutionView>, debugPackageContents: Array<string>, 
/**
 * Keyed by the name a type is stored under.
 */
gameTypes: { [key in string]: GameTypeView }, 
/**
 * The scancode a captured keypress writes, keyed by the browser's `KeyboardEvent.code`.
 */
scancodes: { [key in string]: string }, };
