// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The types here deserialize from what `scripts/gen/gen-catalog.mjs` emits, which is the same data
 * the TypeScript build reads. Field names stay in that file's spelling rather than Rust's, so the
 * generator has one output shape and not two.
 */
export type ChoiceOption = { value: string, label: string, help: string | null, };
