// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The types here deserialize from what `scripts/gen/gen-catalog.mjs` emits, and serialize to the
 * interface in the same shape. Field names stay in that file's spelling rather than Rust's, so the
 * generator and the interface share one shape and not two.
 */
export type ChoiceOption = { value: string, label: string, help: string | null, };
