// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarriedSelection } from "./CarriedSelection";
import type { ChoiceGroup } from "./ChoiceGroup";
import type { ModPart } from "./ModPart";

/**
 * Everything the interface needs to draw a choice it cannot compute: the renderer reads no manifest.
 */
export type ChoiceOffer = { 
/**
 * The groups this release can deliver, in the order the manifest declares them.
 */
groups: Array<ChoiceGroup<ModPart>>, carried: CarriedSelection, };
