// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pick } from "./Pick";

export type ChoiceGroup<T> = { label: string, pick: Pick, options: Array<T>, };
