// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChoiceOptionView } from "./ChoiceOptionView";

/**
 * A setting whose engines have each moved, as the question about it is asked.
 */
export type ChoiceView = { id: string, label: string, 
/**
 * Each value that moved, with the file it moved in.
 */
options: Array<ChoiceOptionView>, };
