// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One key to write. The catalog maps a setting id to this; core does not know what a setting is.
 */
export type ConfigChange = { file: string, section: string, key: string, value: string, };
