// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueTest } from "./ValueTest";

/**
 * A pairing the engine handles badly, warned about only while both settings are in the states
 * named. Unlike a gate, each setting still works alone, so neither is disabled.
 */
export type Conflict = { id: string, 
/**
 * `self` in the emitted data, which Rust cannot name a field.
 */
self: ValueTest, other: ValueTest, note: string, };
