// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pairing in effect that the engine handles badly.
 */
export type ConflictView = { other: string, otherLabel: string, note: string, };
