// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The control the previous interface drew, which a setting's catalog kind alone does not determine.
 */
export type Control = "checkbox" | "slider" | "spin" | "dropdown" | "qinput" | "radio";
