// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameType } from "./GameType";

/**
 * What creating an install would do. Thicker than a delegated base mod's plan, because ZAX performs
 * this one and therefore knows - but still not a file list: ten thousand payload entries are not
 * something anybody reads before pressing a button.
 */
export type CreateInstallPlan = { version: string, 
/**
 * The directory it makes, relative to the host install.
 */
directory: string, asset: string, download: bigint, 
/**
 * What the payload unpacks to, read from its own directory.
 */
unpacked: bigint, 
/**
 * Free bytes on the host's filesystem, where the host could say.
 */
free: bigint | null, 
/**
 * The folders the user pointed at, by input id.
 */
inputs: { [key in string]: string }, 
/**
 * How many paths are lifted out of the user's own archive, counted from the list the payload
 * ships.
 */
extracts: number | null, 
/**
 * The game type the created install reports. The host's own type does not change.
 */
becomes: GameType, fingerprint: string, };
