// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeConflict } from "./MergeConflict";

export type CreateInstallOutcome = { version: string, 
/**
 * The install this made, which the caller registers - identified by reading it, not by the claim
 * here.
 */
created: string, 
/**
 * How many paths were lifted out of the user's archive.
 */
extracted: number, 
/**
 * Paths the list named that the user's archive does not hold, which the extraction went without.
 */
skipped: Array<string>, 
/**
 * Settings both the user and the release changed; the user's won. Empty on a first install.
 */
conflicts: Array<MergeConflict>, };
