// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebugPackage = { 
/**
 * Where the archive was written.
 */
path: string, 
/**
 * What went into it, by the name it has inside the archive.
 */
contents: Array<string>, };
