// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeldTarget } from "./HeldTarget";

/**
 * One linked setting whose addresses do not agree, and what needs doing about it. At most one of
 * `settle` and `choose` is set: neither, where the disagreement has already been accepted and there is
 * nothing left to do - it is still reported, because a caller has to know these addresses differ
 * whether or not it is being asked to act on them.
 */
export type Divergence = { id: string, 
/**
 * Every address taking part, as it now reads. What accepting the disagreement records as the new
 * base: the caller holds no other view of which addresses were weighed, and re-deriving them from
 * the files a second time is a second answer to the same question.
 */
at: Array<HeldTarget>, 
/**
 * The value that survives and where it came from. It is by definition a value ZAX did not write,
 * so the interface says where it came from rather than propagating it silently.
 */
settle: HeldTarget | null, 
/**
 * Two addresses moved since ZAX wrote, so which value survives is the user's to choose, not ZAX's.
 */
choose: Array<HeldTarget> | null, };
