// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A settings entry this version cannot draw, kept so the interface can say so rather than say
 * nothing.
 *
 * The two classes of ignorance are not alike, and this is the second. A field that decides what
 * lands on disk refuses the manifest when unknown, because ignoring it writes the wrong thing. A
 * settings entry only ever edits a key in the mod's own ini, and the release ships its own default
 * there - so a control this version cannot render costs the user a knob and never costs
 * correctness, and refusing the mod over one would make a mod uninstallable for sitting on the
 * wrong side of a ZAX release.
 */
export type DroppedSetting = { 
/**
 * The address the manifest spelled, `section.key`.
 */
address: string, why: string, };
