// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineAsset } from "./EngineAsset";

export type EngineRelease = { 
/**
 * The release's tag, as published.
 */
release: string, 
/**
 * When it was published, ISO 8601.
 */
published: string, 
/**
 * The asset for the machine asking, or nothing when the project publishes no build it can run.
 */
asset: EngineAsset | null, 
/**
 * The commit the tag points at, or nothing where it could not be read. What actually identifies a
 * rolling build: its tag and its release name never change, so the date and this are all that
 * separate one from the next.
 */
commit: string | null, };
