// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CachedBuild } from "./CachedBuild";
import type { MachineBuild } from "./MachineBuild";
import type { ReleaseModel } from "./ReleaseModel";

/**
 * One engine as the Engines tab needs it: what it is, what this machine would install, and which
 * builds it already holds. Nothing here is a game folder's business - what is deployed in one is
 * `deployed_engines`.
 */
export type EngineListing = { id: string, name: string, short: string, page: string, 
/**
 * How the project publishes, which decides whether a build is named to the user by tag or by date.
 */
releases: ReleaseModel, 
/**
 * What would be installed here, or nothing with `why` saying there is none.
 */
build: MachineBuild | null, why: string | null, 
/**
 * What has to be said before running this engine, from the catalog. Absent for one that needs
 * nothing said.
 */
caution: string | null, 
/**
 * What this machine holds, newest first. Empty is an engine nothing has fetched yet.
 */
versions: Array<CachedBuild>, };
