// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One published file: what it is called, where it is, and how big the release says it is.
 */
export type EngineAsset = { name: string, url: string, size: number, };
