// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A feed that could not answer, and why.
 */
export type FeedFailure = { repository: string, id: string, name: string, why: string, };
