// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which mod is installed, decided by reading the directory rather than by anything the user tells
 * us.
 *
 * The four patched types are two pairs, and the distinction is not cosmetic: killap's Unofficial
 * Patch and Restoration Project patch `data/` in place, while the Updated forks that descend from
 * them are separate mods distributed as a `mods/*.dat`. Calling either one "the unofficial patch"
 * mislabels the other.
 *
 * `Fo1In2` is not a fifth patch but a different game: Fallout 1 rebuilt on this engine, in its own
 * directory.
 * Spelled across the boundary exactly as `as_str` spells it for `zax.yml`, so one name identifies a
 * type everywhere rather than one for the file and another for the interface.
 */
export type GameType = "fallout2" | "fallout2up" | "fallout2rp" | "fallout2upu" | "fallout2rpu" | "fo1in2";
