// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one kind of install is called.
 */
export type GameTypeView = { name: string, 
/**
 * The same said in full, for a tooltip.
 */
label: string, badge: string, };
