// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A gate as a row states it: whether it holds, what it waits on, and in what words.
 */
export type GateView = { active: boolean, controller: string, controllerLabel: string, 
/**
 * Where the controller lives, at the address its own row on this tab shows.
 */
controllerFile: string, 
/**
 * The values the gate accepts, phrased for a note.
 */
wants: string, 
/**
 * Whether the gate names exactly one value, which is what lets a fix say only "set it".
 */
single: boolean, };
