// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The test is flattened beside the id, which is how the generator writes it: `{id, is: [..]}`.
 */
export type Gate = { id: string, } & ({ "is": Array<string> } | { "isNot": Array<string> });
