// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A group of settings tabs the install offers, and why its rows take no input where they do not.
 */
export type GroupView = { id: string, refusal: string | null, 
/**
 * Unsaved edits to settings with an address on this group's tabs.
 */
modified: number, };
