// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingTarget } from "./SettingTarget";

/**
 * One address taking part, and what it now says.
 */
export type HeldTarget = { target: SettingTarget, value: string, };
