// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseInstallOutcome } from "./BaseInstallOutcome";
import type { CreateInstallOutcome } from "./CreateInstallOutcome";
import type { ModInstallOutcome } from "./ModInstallOutcome";

/**
 * What one finished install left behind, whichever route ran it.
 */
export type InstallOutcome = { "kind": "stacking" } & ModInstallOutcome | { "kind": "base" } & BaseInstallOutcome | { "kind": "creates" } & CreateInstallOutcome;
