// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModType } from "./ModType";

export type InstalledMod = { 
/**
 * Bound to the manifest's own id shape: it names a working directory, and a record is a file on
 * disk.
 */
id: string, version: string, 
/**
 * The manifest's type as it was validated at install time, and the reason a permanent one gives.
 *
 * Held as its own field rather than read back out of the manifest snapshot below, so a removal
 * is judged against something this version parsed rather than against a document a newer ZAX may
 * have written.
 */
modType: ModType | null, reason: string | null, 
/**
 * False from the first byte deployed until the install finished, so a relaunch offers retry or
 * restore.
 */
complete: boolean, 
/**
 * Deployed paths relative to the install, every one under `mods/` - what uninstall deletes.
 */
files: Array<string>, 
/**
 * The mods-folder entries the release declared, as its manifest spelled them - what uninstall
 * removes from the order file. Held rather than re-derived from `files`, which cannot name a
 * folder entry at all.
 */
entries: Array<string>, 
/**
 * Which parts were chosen, by id. What an upgrade re-installs without asking, and the reason a
 * part id is permanent: a renamed part reads here as one part removed and another added.
 */
parts: Array<string>, 
/**
 * The manifest exactly as the release carried it: schema and state list readable without the
 * network.
 */
manifest: string, 
/**
 * State files as that release shipped them, latin1 text - the base an upgrade's merge compares
 * against. Text rather than bytes because that is what the YAML file holds; a caller merging
 * against them encodes back to latin1 at the boundary.
 */
shipped: { [key in string]: string }, };
