// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameType } from "./GameType";
import type { WineConfig } from "./WineConfig";

export type Install = { path: string, 
/**
 * Named `type` across the boundary, as the interface and `zax.yml` both spell it.
 */
type: GameType, 
/**
 * What the user chose to call this install. `None` means the type's own name, which is what
 * most use.
 */
alias?: string | null, wine?: WineConfig | null, };
