// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseInstallPlan } from "./BaseInstallPlan";
import type { CreateInstallPlan } from "./CreateInstallPlan";
import type { ModInstallPlan } from "./ModInstallPlan";

/**
 * What a plan resolved to, whichever of the three shapes an install takes.
 *
 * Tagged with the kind the TypeScript carried on each of the three plans, so the interface tells them
 * apart by reading one field rather than by which others are present.
 */
export type InstallPlan = { "kind": "stacking" } & ModInstallPlan | { "kind": "base" } & BaseInstallPlan | { "kind": "creates" } & CreateInstallPlan;
