// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An engine ZAX put into this install.
 *
 * Not a mod: it deploys outside `mods/`, so none of the manifest machinery applies to it, and what
 * it needs recording is only what the directory cannot say - which release these bytes are.
 */
export type InstalledEngine = { id: string, 
/**
 * The release's tag, as published. `continious` for a project that republishes one release in
 * place.
 */
release: string, 
/**
 * When that release was published, ISO 8601. The version, where a project publishes none.
 */
published: string, 
/**
 * False from the first byte deployed until the install finished, so a crash is visible as one.
 */
complete: boolean, 
/**
 * Top-level entries deployed into the install, relative to it. A macOS bundle is one directory
 * entry.
 */
files: Array<string>, 
/**
 * Where copies of anything replaced went, absent when nothing was.
 */
backup: string | null, 
/**
 * The commit that release was built from, absent where the project's tag did not resolve to one.
 */
commit: string | null, 
/**
 * True where the user picked this build by name. False means the folder follows the newest build
 * the machine holds, so fetching a newer one moves it forward on the next run.
 */
pinned: boolean, };
