// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallOutcome } from "./InstallOutcome";

/**
 * What an install did, and why a game it created could not be listed, where it could not.
 */
export type InstallReport = { outcome: InstallOutcome, refusedRegistration: string | null, };
