// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the two installer routes a host takes.
 */
export type InstallerRoute = "windows" | "other";
