// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinnedAsset } from "./PinnedAsset";
import type { RecordedMod } from "./RecordedMod";

/**
 * The journal as it sits on disk. Its own shape rather than serde on the types above, because
 * `InstalledMod` carries a YAML value for the fields a newer ZAX may have written and JSON has no
 * place to put one - so the entry travels as the YAML the record itself holds.
 */
export type Journal = { transaction: bigint, id: string, archive?: PinnedAsset | null, parts?: { [key in string]: PinnedAsset } | null, selection?: Array<string> | null, manifestText: string, version: string, previous?: RecordedMod | null, order?: string | null, preexisting: Array<string>, };
