// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutTab } from "./LayoutTab";

export type LayoutFile = { 
/**
 * What identifies this group of tabs and keys which of them is open: the config file's name for
 * the game's own three, the engine's id for an engine's. An engine's tabs are not one file's -
 * fallout2-ce shows both the keys it reads from the game's config and the ones a linked setting
 * puts in the content patch.
 */
id: string, 
/**
 * What the previous interface called it - the component, not the filename.
 */
label: string, 
/**
 * The engine whose settings these tabs show, absent for the game's own three.
 */
engine: string | null, tabs: Array<LayoutTab>, };
