// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Control } from "./Control";

/**
 * A control, a titled group of them, or one of the few widgets that is not a single setting.
 */
export type LayoutNode = { "kind": "setting", id: string, control: Control, 
/**
 * Still placed and still in the catalog, so the key round-trips - just not offered as a
 * choice.
 */
hidden: boolean, } | { "kind": "frame", title: string, items: Array<LayoutNode>, } | { "kind": "widget", id: string, };
