// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingTarget } from "./SettingTarget";

/**
 * Another address a row's value is written to, and whether an edit reaches it now.
 */
export type LinkedAddress = { at: SettingTarget, live: boolean, };
