// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppState } from "./AppState";

export type LoadedState = { state: AppState, 
/**
 * Why the file could not be read, when it could not be. The caller shows this and does not
 * overwrite: an unreadable file replaced by an empty one is the user's install list gone.
 */
problem?: string | null, };
