// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a lock says about itself. Every field is for the message a refusal has to write.
 */
export type LockRecord = { 
/**
 * The machine that took it, which is the only thing a lock on a share can be judged by from
 * elsewhere.
 */
host: string, 
/**
 * The process writing under it - the installer where one is running, ZAX itself until then.
 */
pid: number, 
/**
 * What is being done, so a refusal names the operation rather than only its directory.
 */
what: string, 
/**
 * The program the id was started as, once one has been handed the claim. What it settles is
 * reuse: the system hands ids out again, so an id that is alive may be alive as something with
 * nothing to do with this install, and the command is the only thing that tells those apart.
 */
command?: string | null, 
/**
 * When it was taken, in milliseconds since the epoch. Reported, never used to decide staleness.
 */
taken: number, };
