// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperatingSystem } from "./OperatingSystem";

/**
 * The application's own directories, and which machine this is. Read once, at startup.
 */
export type MachineDescription = { os: OperatingSystem, backupDirectory: string, debugDirectory: string, packageDirectory: string, logFile: string, };
