// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What this machine would install of one engine, where it publishes a build for it.
 */
export type MachineBuild = { asset: string, program: string, };
