// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ZAX owns this value and always writes it. Shown read-only with the reason, rather than hidden, so
 * the choice is visible instead of looking like the setting simply went missing.
 */
export type Managed = { value: string, reason: string, };
