// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A key both sides changed. The user's value is kept; the caller decides whether to say so.
 */
export type MergeConflict = { section: string, key: string, mine: string, theirs: string, };
