// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModKind } from "./ModKind";

export type Mod = { 
/**
 * The entry as the file writes it, relative to `mods\`.
 */
name: string, enabled: boolean, kind: ModKind, 
/**
 * The installed mod this entry belongs to, when the record claims it and only it.
 */
owner: string | null, };
