// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedFailure } from "./FeedFailure";
import type { PublishedMod } from "./PublishedMod";

/**
 * Every feed's current release, and the feeds that could not answer. Read once, not once per install.
 */
export type ModFeedListing = { published: Array<PublishedMod>, failures: Array<FeedFailure>, };
