// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlannedFile } from "./PlannedFile";

/**
 * The resolved plan, shown before anything is written.
 */
export type ModInstallPlan = { files: Array<PlannedFile>, 
/**
 * The mods-folder entries this install owns, as the manifest spells them - added or re-enabled in
 * the order file, and recorded so an uninstall can drop the lines a folder entry's paths could
 * never name.
 */
orderLines: Array<string>, 
/**
 * The parts this plan installs, by id, empty for a mod without them. What the record keeps.
 */
parts: Array<string> | null, 
/**
 * Recorded files the new release does not ship - an upgrade replaces, never overlays.
 */
removes: Array<string>, 
/**
 * What this plan resolved to, in one short string. The install re-plans - the directory may have
 * moved on since the confirmation - and refuses when the answer no longer fingerprints the same,
 * so what runs is what was agreed to rather than whatever the same button would resolve to now.
 */
fingerprint: string, };
