// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A value ZAX must ask the user for, with the file that says the answer is the right one.
 */
export type ModInput = { id: string, label: string, help: string | null, 
/**
 * A file the chosen folder must hold - Fallout 1's `master.dat` for the archive Fo1in2 unpacks.
 */
holds: string, };
