// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModOffer } from "./ModOffer";
import type { Standing } from "./Standing";

/**
 * Where one install stands against the published mods, which is everything a change of game
 * invalidates.
 */
export type ModInstallState = { 
/**
 * By mod id, for the published mods this install could say something about.
 */
standing: { [key in string]: Standing }, 
/**
 * Rows only this install's record knows about, complete as they are drawn - no feed describes them.
 */
unfollowed: Array<ModOffer>, };
