// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A confirmed plan, named by what it was planned from.
 */
export type ModInstallRequest = { modId: string, fingerprint: string, choices: Array<string>, answers: { [key in string]: string }, version: string | null, };
