// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeConflict } from "./MergeConflict";

export type ModInstallOutcome = { version: string, files: Array<string>, 
/**
 * Settings both the user and the release changed; the user's won.
 */
conflicts: Array<MergeConflict>, };
