// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What is on disk under a mod's name. `Missing` is an entry whose file or folder is no longer there.
 */
export type ModKind = "dat" | "folder" | "file" | "missing";
