// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of a repository's parallel release lines. `prefix` is what its versions start with, and
 * `counter` marks the line that the pre-split history belongs to - RPU's bare `v30` and everything
 * below it is 2.3's past, and an install that stamps no version at all is that line's to repair
 * rather than the newer line's to take over.
 */
export type ModLine = { prefix: string, counter: boolean, };
