// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedFailure } from "./FeedFailure";
import type { ModOffer } from "./ModOffer";

export type ModListing = { offers: Array<ModOffer>, 
/**
 * Feeds that could not answer, each with why - offline, no manifest yet, needs a newer ZAX. Base
 * mods only: a stacking mod nobody can read is not news, and four such rows would bury the mods
 * that did answer.
 */
failures: Array<FeedFailure>, };
