// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Availability } from "./Availability";
import type { ChoiceOffer } from "./ChoiceOffer";
import type { GameType } from "./GameType";
import type { ModInput } from "./ModInput";
import type { ModType } from "./ModType";

/**
 * One mod as the interface lists it, everything plain enough to cross the process boundary.
 */
export type ModOffer = { id: string, name: string, version: string, modType: ModType, 
/**
 * What the release says about itself. The pages are flags: the interface asks for one by name.
 */
author: string | null, description: string | null, forum: boolean, homepage: boolean, 
/**
 * A permanent mod's declared reason, standing where the Remove control would be.
 */
reason: string | null, 
/**
 * What a base mod turns this install into, which is the thing worth knowing before installing one.
 */
becomes: GameType | null, 
/**
 * The directory a creating mod makes inside this install, where it makes one.
 */
creates: string | null, 
/**
 * What the user must be asked for before this can be installed, so the interface reads no manifest.
 */
asks: Array<ModInput>, 
/**
 * The choice to make before installing this release, and where this install stands in it.
 */
choices: ChoiceOffer | null, 
/**
 * Set on a row the record alone describes, where no feed follows the mod: `version` is then what is
 * on disk rather than what is offered. Both readings otherwise have the same shape, and a retry row
 * arrives either way, so nothing downstream could tell an offered version from an installed one
 * without this.
 */
noFeed: boolean, availability: Availability, };
