// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An installed mod as the order list needs it: what to call it, and what it put in the mods folder.
 */
export type ModOwner = { name: string, 
/**
 * Deployed paths as the record holds them - relative to the install, and under `mods/`.
 */
files: Array<string>, };
