// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One choice inside a group.
 *
 * A part names its own release asset, because that is what every real case is - four zips, four
 * dats, two zips - and no part is ever a subset of another's archive, so nothing here slices an
 * archive up.
 */
export type ModPart = { 
/**
 * Permanent the way the mod's id is: the recorded selection names it, so a rename reads as a
 * new part.
 */
id: string, label: string, help: string | null, 
/**
 * The release asset this part deploys - its own download, its own digest, its own preflight.
 */
archive: string, 
/**
 * What this part puts in the mods folder, read exactly as the mod's own entries are.
 */
entries: Array<string> | null, 
/**
 * Another part this one is meaningless without - Cassidy's voices without its head.
 */
needs: string | null, };
