// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of a mod's own pages to open.
 */
export type ModPage = "forum" | "homepage";
