// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModRemoval = { 
/**
 * What was deleted, relative to the install.
 */
files: Array<string>, 
/**
 * Where the copies went before deletion.
 */
backup: string, };
