// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingDef } from "./SettingDef";

/**
 * A mod setting is a catalog definition plus the value the release ships, kept for revert and
 * display.
 */
export type ModSetting = { def: SettingDef, default: string | null, };
