// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModKind } from "./ModKind";

/**
 * Something in the mods folder that the engine could load.
 */
export type ModsDirEntry = { name: string, kind: ModKind, };
