// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DroppedSetting } from "./DroppedSetting";
import type { ModSetting } from "./ModSetting";

/**
 * One installed mod's configuration surface: who it belongs to, and the schema its record carries.
 */
export type ModSettingsGroup = { modId: string, name: string, 
/**
 * The ini files the schema describes - what the open-the-file affordance opens.
 */
files: Array<string>, settings: Array<ModSetting>, 
/**
 * Entries the schema declares that this version cannot draw. Carried so the surface can say what
 * is missing and why: a control quietly absent reads as a mod that never offered it.
 */
dropped: Array<DroppedSetting>, };
