// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModOwner } from "./ModOwner";
import type { ModsDirEntry } from "./ModsDirEntry";
import type { OrderClaim } from "./OrderClaim";
import type { OrderFormat } from "./OrderFormat";

export type ModsSnapshot = { 
/**
 * The order file exactly as read, or `None` when the install has none.
 */
text: string | null, 
/**
 * Which engine's format that text is in. sfall for a folder with no order file at all.
 *
 * Reported rather than corrected: the file is the user's, and rewriting it because they opened a
 * tab is a write they did not ask for - it also races an engine ZAX has just started for the file
 * it is reading.
 */
format: OrderFormat | null, 
/**
 * Every name that resolves: what the folder holds, plus anything the file names that exists.
 */
present: Array<ModsDirEntry>, 
/**
 * What ZAX installed here. The folder cannot say who put a dat there, so this is the only thing
 * that can tell one a mod deployed from one the user dropped in by hand.
 */
owners: Array<ModOwner>, 
/**
 * What the installed mods say about where they load.
 */
claims: Array<OrderClaim>, };
