// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mod } from "./Mod";

export type ModsSaveRequest = { installPath: string, 
/**
 * The text the edits were made against, as the read answered it.
 */
original: string | null, mods: Array<Mod>, };
