// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What installing this mod does to the install.
 *
 * Pluggable stacks and comes off again, permanent stacks and never does, base transforms the game
 * into another one - which is why only a base mod names an installer.
 */
export type ModType = "pluggable" | "permanent" | "base";
