// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bounds and presentation for a numeric setting.
 *
 * `sentinels` name values that are not quantities - 0 meaning "native", -1 meaning "auto".
 */
export type NumericKind = { min: number | null, max: number | null, unit: string | null, sentinels: { [key in string]: string }, };
