// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModPage } from "./ModPage";
import type { OwnDirectory } from "./OwnDirectory";

/**
 * Somewhere the desktop's own handler is asked to open. Named for the same reason: a mod's page is
 * asked for by naming which page of which mod, never by handing over the address, so what is opened is
 * always something ZAX itself read rather than something a caller supplied.
 */
export type OpenTarget = { "what": "own", directory: OwnDirectory, } | { "what": "log" } | { "what": "download" } | { "what": "mod", id: string, page: ModPage, };
