// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far a long operation has got, in the words the interface shows. Plain fields because it crosses
 * a process boundary on the desktop.
 */
export type OperationProgress = { 
/**
 * What is happening now - "Downloading sfall 4.5".
 */
step: string, 
/**
 * Bytes so far and bytes expected, when the step is a transfer and the server said how big it is.
 */
received: bigint | null, total: bigint | null, 
/**
 * Whether `cancel` would reach this step. Declared rather than inferred from the byte counts being
 * present: the interface offers the button on this, and a control that is offered and does nothing
 * is worse than one that was never there.
 */
cancellable: boolean, };
