// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Spelled across the command boundary the way [`fmt::Display`] spells it, so the interface reads one
 * name for a system rather than one per surface.
 */
export type OperatingSystem = "windows" | "macos" | "linux";
