// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderFormat } from "./OrderFormat";

/**
 * What a launch would change about the mod order, when it would change anything.
 */
export type OrderSwap = { 
/**
 * The format the file is in now, and the one the engine about to run reads.
 */
from: OrderFormat, to: OrderFormat, 
/**
 * Loading now and not after, by the name each has in the mods folder.
 */
losing: Array<string>, 
/**
 * Loading after and not now.
 */
gaining: Array<string>, };
