// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an installed mod says its own entries load, as its manifest declares it.
 *
 * One claim per mod rather than per entry: a mod that deploys several states one place for all of
 * them.
 */
export type OrderClaim = { 
/**
 * The entries the claim places, spelled as the order file names them.
 */
entries: Array<string>, 
/**
 * Entries its own files win over, and entries that win over its own.
 */
overrides: Array<string>, overriddenBy: Array<string>, };
