// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One edit to a mod order.
 */
export type OrderEdit = { "edit": "toggle", name: string, } | { "edit": "shift", name: string, by: number, } | { "edit": "sort" } | { "edit": "forget", name: string, } | { "edit": "forgetMissing" };
