// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mod } from "./Mod";
import type { OrderFormat } from "./OrderFormat";

/**
 * The order as the Mods tab draws it.
 */
export type OrderView = { format: OrderFormat, 
/**
 * Why the tab is closed, or `None` while it is open. One sentence naming the way out: a disabled
 * tab with no reason is a defect rather than a state.
 */
closed: string | null, mods: Array<Mod>, changed: boolean, 
/**
 * The entries loading against the recommendation - the warning, and what sorting moves.
 */
against: Array<string>, 
/**
 * Entries whose files are gone, which is what Forget is offered for.
 */
missing: Array<string>, 
/**
 * The folder split by whether Fission would load each entry.
 */
fissionMods: Array<string>, 
/**
 * Present and invisible to Fission. An entry whose file is gone is not among them: the order list
 * is where a dead entry is dealt with.
 */
fissionMissed: Array<string>, };
