// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the two mutually unreadable formats a mod order file is in.
 *
 * sfall names a path per line; Fission writes pipe-separated records and skips every line without a
 * pipe, so neither reader tolerates the other's file and each rewrites the whole thing into its own.
 */
export type OrderFormat = "sfall" | "fission";
