// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of ZAX's own directories, named rather than passed as a path so a renderer cannot ask for
 * another.
 */
export type OwnDirectory = "backup" | "debug" | "packages";
