// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where one payload came from, kept verbatim so a retry fetches what the first attempt did.
 */
export type PinnedAsset = { name: string, url: string, digest: string, };
