// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlannedFile = { 
/**
 * Relative to the install, under `mods/`.
 */
path: string, size: bigint, 
/**
 * Whether something already sits at the target - what restore would put back.
 */
overwrites: boolean, 
/**
 * Which part ships it, for a mod that has them: deployment takes each file from its own payload.
 */
part: string | null, };
