// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChoiceGroup } from "./ChoiceGroup";
import type { GameType } from "./GameType";
import type { ModInput } from "./ModInput";
import type { ModPart } from "./ModPart";
import type { ModType } from "./ModType";

/**
 * What one feed has published, with nothing of any install in it - a repository publishes one release,
 * whichever game folder is on screen. This is the half of an offer that survives a change of game.
 */
export type PublishedMod = { id: string, name: string, version: string, modType: ModType, 
/**
 * What the release says about itself, for the row offering it. Absent where the manifest says
 * nothing.
 */
author: string | null, description: string | null, 
/**
 * Whether the mod publishes each page, rather than where: the address is the backend's to resolve.
 */
forum: boolean, homepage: boolean, reason: string | null, becomes: GameType | null, creates: string | null, asks: Array<ModInput>, 
/**
 * The choice this release offers, without an install's answer to it. Empty where it offers none.
 */
choice: Array<ChoiceGroup<ModPart>>, };
