// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionView } from "./ActionView";
import type { Divergence } from "./Divergence";
import type { GroupView } from "./GroupView";
import type { InstalledEngine } from "./InstalledEngine";
import type { ModListing } from "./ModListing";
import type { ModSettingsGroup } from "./ModSettingsGroup";
import type { OrderView } from "./OrderView";
import type { RowView } from "./RowView";
import type { SettingDef } from "./SettingDef";

/**
 * The selected install as the interface draws it.
 */
export type ReadingView = { path: string, 
/**
 * The config files this install has.
 */
files: Array<string>, 
/**
 * Where this is set, `rows` holds only the rows that changed since the view of that revision, and
 * `discovered` and `mod_settings` are absent, having not changed. A caller that does not hold that
 * view asks for a whole one.
 */
since: number | null, 
/**
 * Keys the files hold that the catalog does not describe.
 */
discovered: Array<SettingDef> | null, modSettings: Array<ModSettingsGroup> | null, rows: { [key in string]: RowView }, groups: Array<GroupView>, actions: Array<ActionView>, 
/**
 * Linked settings whose engines have each moved, so which value survives is the user's call.
 */
choices: Array<Divergence>, carry: string | null, 
/**
 * Unsaved edits, the mod order counting once however much of it moved.
 */
modifiedCount: number, settingsChanged: boolean, modSettingsChanged: boolean, order: OrderView, sfall: string | null, 
/**
 * Whether a newer sfall has been found than the one installed.
 */
sfallOutdated: boolean, hires: string | null, 
/**
 * What is deployed in the folder, by engine id.
 */
engines: { [key in string]: InstalledEngine }, 
/**
 * Whether the deployed build is behind what a check found, by engine id.
 */
engineOutdated: { [key in string]: boolean }, 
/**
 * The published mods against this install, once the feeds have been read.
 */
modListing: ModListing | null, 
/**
 * Offers whose install is this installation itself rather than a folder inside it.
 */
createsInPlace: Array<string>, };
