// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One record entry as the journal writes it.
 */
export type RecordedMod = { id: string, version: string, type?: string | null, reason?: string | null, complete: boolean, files: Array<string>, entries: Array<string>, parts: Array<string>, manifest: string, shipped: { [key in string]: string }, 
/**
 * The fields the record could not interpret, as the YAML document they were read from - the one
 * representation that cannot lose a value JSON has no type for.
 */
carried?: string, };
