// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeldTarget } from "./HeldTarget";

/**
 * An answer this reading put in front of the user, and everything undoing it needs to know.
 */
export type Reconciled = { 
/**
 * The file a carried value came from, which the row names. Absent where the user picked between
 * two that had both moved: they know where their own answer came from.
 */
from: string | null, 
/**
 * Every address weighed, as it then read - the base a revert of the answer accepts.
 */
at: Array<HeldTarget>, };
