// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallerRoute } from "./InstallerRoute";
import type { ReleaseAsset } from "./ReleaseAsset";

/**
 * A base mod's installer for the platform ZAX is running on, and which of the two routes it is.
 */
export type ReleaseInstaller = { route: InstallerRoute, asset: ReleaseAsset, };
