// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReleaseAsset = { name: string, url: string, 
/**
 * GitHub states `sha256:<hex>`; kept verbatim and split where it is checked.
 */
digest: string | null, size: number | null, };
