// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a project publishes. `Rolling` republishes one release in place and carries no version number,
 * so its publication time is its version; `Tagged` names versions that can be compared.
 */
export type ReleaseModel = "rolling" | "tagged";
