// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A key the release retired that the user had left at the old default, so it is gone from the
 * result.
 */
export type RemovedKey = { section: string, key: string, };
