// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One setting that has to change before another takes effect.
 */
export type Requirement = { id: string, label: string, file: string, value: string, valueLabel: string, wants: string, };
