// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One offered shortcut for the high-resolution patch's width and height pair.
 */
export type ResolutionView = { width: number, height: number, note: string | null, };
