// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressView } from "./AddressView";
import type { ConflictView } from "./ConflictView";

/**
 * Everything one row draws about one setting.
 */
export type RowView = { 
/**
 * The value the control shows: the pending edit where there is one, the file's otherwise.
 */
value: string | null, modified: boolean, 
/**
 * The key is not in the file at all, so the component uses its own default.
 */
absent: boolean, display: string, 
/**
 * What a value ZAX pins reads as, for the setting that has one.
 */
pinned: string | null, 
/**
 * The value as its slider's percentage, for a scale setting.
 */
percent: number | null, sentinel: string | null, 
/**
 * Why the value is not one the component accepts.
 */
invalid: string | null, carriedFrom: string | null, conflict: ConflictView | null, 
/**
 * The group whose address is the setting's own, which is what a row outside any group shows.
 */
ownGroup: string, 
/**
 * Keyed by group: the setting's own, and every other group holding one of its addresses.
 */
groups: { [key in string]: AddressView }, };
