// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigChange } from "./ConfigChange";

export type SaveRequest = { installPath: string, 
/**
 * The contents the edits were made against, as [`load_config_files`] answered.
 */
original: { [key in string]: Array<number> | null }, changes: Array<ConfigChange>, 
/**
 * The same map [`load_config_files`] was given, so a save writes where the read read.
 */
paths: { [key in string]: string }, };
