// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a save did not write, and why, where it wrote nothing.
 */
export type SaveRefusal = { text: string, };
