// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Crosses the boundary as `{"written": [...]}` or `{"stale": [...]}`: which of the two happened is
 * the whole answer, and a shape that says so in the tag cannot be read as the other by mistake.
 */
export type SaveOutcome = { "written": Array<string> } | { "stale": Array<string> };
