// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchResult } from "./SearchResult";

export type SearchResults = { results: Array<SearchResult>, 
/**
 * Whether the install tab answers the query. It holds nothing from the catalog, so without this a
 * search for "wine" would report nothing while the tab sits in plain view.
 */
installMatches: boolean, };
