// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a search result lives, which is where going to it lands.
 */
export type SearchResult = { id: string, group: string, tab: string, 
/**
 * "Sfall / Main / Graphics": the address, since the row has left the tab that located it.
 */
place: string, };
