// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChoiceOption } from "./ChoiceOption";
import type { NumericKind } from "./NumericKind";

export type SettingKind = { "type": "scale", max: number, } | { "type": "bool", onValue: string, offValue: string, } | { "type": "int" } & NumericKind | { "type": "float" } & NumericKind | { "type": "text", path: boolean, } | { "type": "choice", options: Array<ChoiceOption>, } | { "type": "key" };
