// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Conflict } from "./Conflict";
import type { Managed } from "./Managed";
import type { SettingKind } from "./SettingKind";
import type { Targets } from "./Targets";

export type SettingDef = { id: string, targets: Targets, kind: SettingKind, label: string, help: string | null, conflictsWith: Conflict | null, managed: Managed | null, };
