// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gate } from "./Gate";

/**
 * One address a setting's value lives at.
 *
 * Most settings have a single target; a setting that more than one engine carries under its own
 * name has one per engine, so that the several names stay one row.
 */
export type SettingTarget = { file: string, section: string, key: string, 
/**
 * The engine whose settings this address belongs to, absent where it is the game's own,
 * sfall's or the high-resolution patch's. Not something the file and section imply:
 * fallout2-ce writes keys of its own into the game's `[system]` and `[sound]`, beside vanilla
 * keys that belong to no engine.
 */
engine: string | null, 
/**
 * This target only takes effect while another setting passes the test. Editing it otherwise
 * changes the file but not the game, so the interface says so rather than letting the change
 * look effective. Per target rather than per setting: a prerequisite can hold on one engine and
 * not on the next, and a shared gate would either over-restrict the others or write a value
 * that silently does nothing.
 */
gatedBy: Gate | null, };
