// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingValue } from "./SettingValue";

/**
 * One edit to a setting: a value as the file holds it, or a scale's value as its slider shows it.
 */
export type SettingEdit = { id: string, to: SettingValue, };
