// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeConflict } from "./MergeConflict";
import type { RemovedKey } from "./RemovedKey";

export type SfallUpdate = { version: string, 
/**
 * Files replaced in the game folder, relative to it.
 */
replaced: Array<string>, 
/**
 * Where the replaced copies were put, or `None` when the update added files without replacing
 * any.
 */
backup: string | null, 
/**
 * Settings both the user and the release changed. The user's won; these are worth a second look.
 */
conflicts: Array<MergeConflict>, 
/**
 * Settings the release retired that the user had left at the old default.
 */
removed: Array<RemovedKey>, };
