// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppView } from "./AppView";

/**
 * What starting up found.
 */
export type Started = { view: AppView, 
/**
 * Why the state file could not be read, when it could not be.
 */
problem: string | null, };
