// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WineConfig } from "./WineConfig";

export type StoredInstall = { path: string, 
/**
 * Only what the user typed: an install left at its type's name stores nothing, so it follows
 * the type.
 */
alias?: string | null, wine?: WineConfig | null, };
