// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingTarget } from "./SettingTarget";

/**
 * Every address one value is written to, the nominated one first.
 *
 * A separate type because the first target is the address the id was minted from, so it stays the
 * id's source even where its file is absent. Holding it apart is what lets [`Targets::own`] answer
 * without a fallible lookup, which is the guarantee the TypeScript got from a non-empty tuple type.
 */
export type Targets = { own: SettingTarget, others: Array<SettingTarget>, };
