// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which values of a setting a rule applies to.
 *
 * `IsNot` covers controllers with an open range, where the interesting states cannot be listed: "a
 * key is bound" is every value but none, and "idling is on" is every value but the disabled
 * sentinel.
 * Externally tagged, which is what spells these as `{"is": [..]}` and `{"isNot": [..]}` - the shape
 * the generator writes.
 */
export type ValueTest = { "is": Array<string> } | { "isNot": Array<string> };
