// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an action leaves in the install's `WINEDEBUG`, for the two that are about logging.
 *
 * It belongs to the install's own record rather than to a config file, so it is written at once
 * where the targets stay pending.
 */
export type WineSetting = { debug: string, };
