// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wine settings are per install rather than global: one install can be a Windows build under its
 * own prefix while another is native, and a prefix that is right for one is wrong for the other.
 */
export type WineConfig = { prefix?: string | null, debug?: string | null, };
