// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OwnDirectory } from "./OwnDirectory";

/**
 * Something of ZAX's own the user can empty. The log is a file rather than a directory, hence its own
 * arm.
 */
export type WipeTarget = { "what": "own", directory: OwnDirectory, } | { "what": "log" };
