// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ZaxRelease = { version: string, 
/**
 * The build for the machine asking, or the release page when it publishes nothing that machine
 * can run.
 */
url: string, };
