f2gm:
  path: f2_res.ini
  name: HiRes

MAIN:
  UAC_AWARE:
    name: UAC aware
  GRAPHICS_MODE:
    name: Graphics mode
    display_type: dropdown
    options:
      - value: 0
        name: Resolution only
        desc: Required for sfall's Graphic modes
      - value: 1
        name: Direct Draw 7
      - value: 2
        name: DirectX9
  SCALE_2X:
    name: Scale x2 # todo: increase min res x2
  # SCR_WIDTH: # todo: full screen only
  #   name: Resolution X
  #   type: int
  #   min: 640
  # SCR_HEIGHT:
  #   name: Resolution Y
  #   type: int
  #   min: 480
  resolution:
    type: dropdown
    options:
      - value: 1920x1080
        name: '1920x1080'
      - value: 1366×768
        name: '1366×768'
      - value: 1280x1024
        name: '1280x1024'
      - value: 1280x800
        name: '1280x800'
      - value: 1280x720
        name: '1280x720'
      - value: 1152x864
        name: '1152x864'
      - value: 1024x768
        name: '1024x768'
      - value: 1024x576
        name: '1024x576'
      - value: 960x720
        name: '960x720'
      - value: 960x600
        name: '960x600'
      - value: 960x540
        name: '960x540'
      - value: 800x600
        name: '800x600'
      - value: 640x480
        name: '640x480'
  COLOUR_BITS:
    name: Color depth
    display_type: dropdown
    options:
      - value: 8
        name: '8'
      - value: 16
        name: '16'
      - value: 32
        name: '32'
  REFRESH_RATE:
    name: Monitor refresh rate
    type: int
    min: 60
  WINDOWED:
    name: Window mode
    display_type: radio
    options:
      - value: 0
        name: Fullscreen
      - value: 1
        name: Windowed
      # - Windowed fullscreen
  # WIN_DATA: # some voodoo
  f2_res_dat:
    type: string
  f2_res_patches:
    type: string
  WINDOWED_FULLSCREEN: # todo: merge into windowed

INPUT:
  ALT_MOUSE_INPUT:
    name: Alternative mouse input
  EXTRA_WIN_MSG_CHECKS:
    name: Extra Windows msg checks
  SCROLLWHEEL_FOCUS_PRIMARY_MENU:

EFFECTS:
  IS_GRAY_SCALE:
    name: Grayscale

HI_RES_PANEL:
  DISPLAY_LIST_DESCENDING:

MOVIES:
  MOVIE_SIZE:
    name: Movie size
    display_type: radio
    options:
      - value: 0
        name: Original
      - value: 1
        name: Stretched maintaining ratio
      - value: 2
        name: Stretched

MAPS:
  EDGE_CLIPPING_ON:
  IGNORE_MAP_EDGES:
  IGNORE_PLAYER_SCROLL_LIMITS:
  SCROLL_DIST_X:
    type: string
    min: 480
  SCROLL_DIST_Y:
    type: string
    min: 400
  NumPathNodes:
    type: int
    min: 1
    max: 20
  FOG_OF_WAR:
    name: Fog of war
  FOG_LIGHT_LEVEL:
    type: int
    min: 0
    max: 10

  # ZOOM_LEVEL: # these are from dev build?
  # IS_ZOOM_BOUND_BY_EDGES:

IFACE:
  IFACE_BAR_MODE:
    name: Map window position from interface bar
    display_type: radio
    options:
      - value: 0
        name: On top
      - value: 1
        name: Overlaps
  IFACE_BAR_SIDE_ART:
    display_type: radio
    options:
      - value: 0
        name: None (black)
      - value: 1
        name: Metal
      - value: 2
        name: Leather
  IFACE_BAR_SIDES_ORI:
    name: Interface bar art orientation
    display_type: radio
    options:
      - value: 0
        name: Bar > Edge
      - value: 1
        name: Edge > Bar
  IFACE_BAR_WIDTH:
    name: Interface bar width
    type: int
    min: 640
  ALTERNATE_AMMO_METRE:
    name: Alternate ammo metre
    desc: The following settings set the palette offsets of particular colours used when this is set to Single colour.
    display_type: dropdown
    options:
      - value: 0
        name: Disabled
      - value: 1
        name: Single colour
      - value: 2
        name: Changing colour
      - value: 3
        name: Coloured sections
  ALTERNATE_AMMO_LIGHT: # todo: enable only when ALTERNATE_AMMO_METRE==1?
    name: Main color
    type: int
  ALTERNATE_AMMO_DARK:
    name: Dark color
    type: int

MAINMENU:
  MAIN_MENU_SIZE:
    name: Size
    display_type: radio
    options:
      - value: 0
        name: Original
      - value: 1
        name: Stretch maintaining ratio
      - value: 2
        name: Stretch
  USE_HIRES_IMAGES:
    name: High resolution images
  SCALE_BUTTONS_AND_TEXT_MENU:
    name: Scale Buttons and text menu
  MENU_BG_OFFSET_X:
    type: string
  MENU_BG_OFFSET_Y:
    type: string

# STATIC_SCREENS:
#   DEATH_SCRN_SIZE:
#   END_SLIDE_SIZE:
#   HELP_SCRN_SIZE:
#   SPLASH_SCRN_SIZE:

# OTHER_SETTINGS:
#   CD_CHECK:
#   DIALOG_SCRN_BACKGROUND:
#   DIALOG_SCRN_ART_FIX:
#   SPLASH_SCRN_TIME:
#   CPU_USAGE_FIX:
#   BARTER_PC_INV_DROP_FIX:
#   FADE_TIME_MODIFIER:
#   FADE_TIME_RECALCULATE_ON_FADE:
