f2gm:
  path: fallout2.cfg
  name: Game

debug:
  output_map_data_info:
  show_load_info:
  show_script_messages:
  show_tile_num:

preferences:
  brightness:
    type: slider
    value_type: float
    float_base: 1000000
    min: 1
    max: 1.179993
  combat_difficulty:
    name: Difficulty
    type: dropdown
    options:
      - value: 0
        name: Wimpy
      - value: 1
        name: Normal
      - value: 2
        name: Rough
  combat_looks:
    name: Looks
  combat_messages:
    name: Messages
    type: radio
    options:
      - value: 0
        name: Verbose
      - value: 1
        name: Brief
  combat_speed:
    name: Speed
    type: slider
    min: 0
    max: 50
  combat_taunts:
    name: Taunts
  game_difficulty:
    name: Difficulty
    type: radio
    options:
      - value: 0
        name: Easy
      - value: 1
        name: Normal
      - value: 2
        name: Hard
  item_highlight:
    name: Highlight items
  language_filter:
    name: Language filter
  mouse_sensitivity:
    name: Mouse sensitivity
    type: slider
    min: 1
    max: 2.5
    data_type: float
    float_base: 1000000
  player_speedup:
    name: Affect player speed
  running:
    name: Always run
  subtitles:
  target_highlight:
    name: Highlight target
  text_base_delay:
    type: slider
    min: 1
    max: 6
    data_type: float
    float_base: 1000000
  text_line_delay:
    type: slider
    min: 0
    max: 2
    data_type: float
    float_base: 1000000
  violence_level:
    name: Violence level
    type: dropdown
    options:
      - value: 0
        name: None
      - value: 1
        name: Minimal
      - value: 2
        name: Normal
      - value: 3
        name: Maximum blood

sound:
  cache_size:
    type: int
  device:
    type: int
  dma:
    type: int
  initialize:
  irq:
    type: int
  master_volume:
    type: slider
    min: 1
    max: 22281
  music:
  music_path1:
    type: string
  music_path2:
    type: string
  music_volume:
    type: slider
    min: 1
    max: 22281
  port:
    type: int
  sndfx_volume:
    type: slider
    min: 1
    max: 22281
  sounds:
  speech:
  speech_volume:
    type: slider
    min: 1
    max: 22281
  debug:
  debug_sfxc:

system:
  art_cache_size:
    type: spin
  color_cycling:
  critter_dat:
    type: string
  critter_patches:
    type: string
  cycle_speed_factor:
    type: int
  executable:
    type: string
  free_space:
    type: spin
  hashing:
  interrupt_walk:
  language:
    type: string
  master_dat:
    type: string
  master_patches:
    type: string
  scroll_lock:
  splash:
    type: spin
