f2gm:
  path: fallout2.cfg
  name: Game

debug:
  output_map_data_info:
  show_load_info:
  show_script_messages:
  show_tile_num:

preferences:
  brightness:
    type: slider
    value_type: float
    float_base: 1000000
    min: 1
    max: 1.179993
  combat_difficulty:
    name: Difficulty
    type: dropdown
    options:
      - value: 0
        name: Wimpy
      - value: 1
        name: Normal
      - value: 2
        name: Rough
  combat_looks:
    name: Looks
  combat_messages:
    name: Messages
    type: radio
    options:
      - value: 0
        name: Verbose
      - value: 1
        name: Brief
  combat_speed:
    name: Speed
    type: slider
    min: 0
    max: 50
  combat_taunts:
    name: Taunts

sound:
  cache_size:
    type: int
  device:
  debug:
  debug_sfxc:

  # - name: preferences
  #   keys:
  #     - key: brightness
  #       type: slider
  #       value_type: float
  #       float_base: 1000000
  #       min: 1
  #       max: 1.179993
  #     - key: game_difficulty
  #       name: Difficulty
  #       type: radio
  #       options:
  #         - value: 0
  #           name: Easy
  #         - value: 1
  #           name: Normal
  #         - value: 2
  #           name: Hard
  #     - key: item_highlight
  #       name: Highlight items
  #     - key: language_filter
  #       name: Language filter
  #     - key: mouse_sensitivity
  #       name: Mouse sensitivity
  #       type: slider
  #       min: 1
  #       max: 2.5
  #       data_type: float
  #       float_base: 1000000
  #     - key: player_speedup
  #       name: Affect player speed
  #     - key: running
  #       name: Always run
  #     - key: subtitles
  #     - key: target_highlight
  #       name: Highlight target
  #     - key: text_base_delay
  #       type: slider
  #       min: 1
  #       max: 6
  #       data_type: float
  #       float_base: 1000000
  #     - key: text_line_delay
  #       type: slider
  #       min: 0
  #       max: 2
  #       data_type: float
  #       float_base: 1000000
  #       inverted: true
  #     - key: violence_level
  #       name: Violence level
  #       type: dropdown
  #       options:
  #         - value: 0
  #           name: None
  #         - value: 1
  #           name: Minimal
  #         - value: 2
  #           name: Normal
  #         - value: 3
  #           name: Maximum blood
